### ISSUE TITLE
较大的包下载过程出错

### ISSUE THREAD

**Issue by zsy5172** [soulteary/apt-proxy#14]
docker环境下，以较慢的速度(kb/s)下载大文件的时候，时不时会出错

```
2022/11/23 09:11:21 172.31.1.82 "GET http://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/main/n/networkd-dispatcher/networkd-dispatcher_2.1-2%7eubuntu20.04.3_all.deb HTTP/1.1" (OK) 15476 MISS 454.480627ms
2022/11/23 09:11:21 rewrote "/ubuntu/pool/main/s/systemd/udev_245.4-4ubuntu3.19_amd64.deb" to "http://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/main/s/systemd/udev_245.4-4ubuntu3.19_amd64.deb"
2022/11/23 09:12:13 rewrote "/ubuntu/pool/main/s/systemd/udev_245.4-4ubuntu3.19_amd64.deb" to "http://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/main/s/systemd/udev_245.4-4ubuntu3.19_amd64.deb"
panic: net/http: abort Handler
goroutine 760 [running]:
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc000262e60, {0x79ef78?, 0xc000016510}, 0xc0002f0000)
	/opt/hostedtoolcache/go/1.19.2/x64/src/net/http/httputil/reverseproxy.go:363 +0xee9
github.com/soulteary/apt-proxy/pkg/httpcache.(*Handler).passUpstream.func1()
	/home/runner/work/apt-proxy/apt-proxy/pkg/httpcache/handler.go:253 +0x3d
created by github.com/soulteary/apt-proxy/pkg/httpcache.(*Handler).passUpstream
	/home/runner/work/apt-proxy/apt-proxy/pkg/httpcache/handler.go:252 +0x1fb
```

**Comment by soulteary** [comment]
@zsy5172 

感谢反馈，推测和 “timeout” 有关。我试试模拟下较慢速度 lol

**Comment by JoeyZhu** [comment]
类似问题：
2023/02/01 22:25:54 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/main/a/avahi/avahi-daemon_0.7-3.1ubuntu1.3_arm64.deb HTTP/1.1" (OK) 56156 ^[[31;1mMISS^[[0m 1.140665658s
2023/02/01 22:25:55 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/main/a/avahi/avahi-utils_0.7-3.1ubuntu1.3_arm64.deb HTTP/1.1" (OK) 22200 ^[[31;1mMISS^[[0m 1.026803982s
2023/02/01 22:25:59 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/main/b/binutils/binutils-common_2.30-21ubuntu1%7e18.04.8_arm64.deb HTTP/1.1" (OK) 196816 ^[[31;1mMISS^[[0m 3.791026443s
2023/02/01 22:26:00 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/main/b/binutils/binutils_2.30-21ubuntu1%7e18.04.8_arm64.deb HTTP/1.1" (OK) 3364 ^[[31;1mMISS^[[0m 486.296309ms
2023/02/01 22:26:05 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/main/b/binutils/binutils-aarch64-linux-gnu_2.30-21ubuntu1%7e18.04.8_arm64.deb HTTP/1.1" (OK) 2167732 ^[[31;1mMISS^[[0m 5.246591655s
2023/02/01 22:26:08 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/main/b/binutils/libbinutils_2.30-21ubuntu1%7e18.04.8_arm64.deb HTTP/1.1" (OK) 416460 ^[[31;1mMISS^[[0m 3.400437817s
2023/02/01 22:26:11 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/main/b/bluez/bluez-obexd_5.48-0ubuntu3.9_arm64.deb HTTP/1.1" (OK) 141384 ^[[31;1mMISS^[[0m 2.260814118s
2023/02/01 22:26:16 192.168.2.144 "GET http://ports.ubuntu.com/ubuntu-ports/pool/universe/r/runc/runc_1.1.0-0ubuntu1%7e18.04.1_arm64.deb HTTP/1.1" (OK) 3329220 ^[[31;1mMISS^[[0m 5.402605655s
2023/02/01 22:28:12 httputil: ReverseProxy read error during body copy: read tcp 192.168.2.171:41000->185.125.190.36:80: read: connection reset by peer
panic: net/http: abort Handler

goroutine 3790 [running]:
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc00056a820, {0x79efb8?, 0xc0001aa1b0}, 0xc0000d2000)
        /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/httputil/reverseproxy.go:363 +0xee9
github.com/soulteary/apt-proxy/pkg/httpcache.(*Handler).passUpstream.func1()
        /home/runner/work/apt-proxy/apt-proxy/pkg/httpcache/handler.go:253 +0x3d
created by github.com/soulteary/apt-proxy/pkg/httpcache.(*Handler).passUpstream
        /home/runner/work/apt-proxy/apt-proxy/pkg/httpcache/handler.go:252 +0x1fb

**Comment by soulteary** [comment]
这是一个合理且影响较高的可靠性问题，先继续保持开启。

Issue 中的调用栈来自早期内置 `pkg/httpcache` 实现；当前主分支已改用 `httpcache-kit v2.0.1`，并调整了慢速下载相关的超时和请求生命周期，但现有信息不足以确认问题已经彻底消失。

请尽量使用最新版本复测，并补充以下信息：apt-proxy 版本、容器镜像标签、限速方式和大致速率、失败文件大小、客户端错误，以及同一时间段完整服务端日志。后续验收会覆盖慢速上游、大文件传输、客户端中断和上游连接重置；确认当前实现不再 panic 后再关闭。

**Comment by soulteary** [comment]
报告的 panic 来自 pkg/httpcache/handler.go:253，那里在独立 goroutine 里调 ReverseProxy.ServeHTTP，ErrAbortHandler 逃逸导致进程崩。

现在 pkg/ 整个目录不存在，代理路径里 go func 数量为 0，另外加了 RetryableTransport（3 次重试 + 指数退避），ResponseHeaderTimeout 也只卡响应头不卡整体传输（对大文件是对的）。
