### ISSUE TITLE
在centos不支持的代理下服务会挂掉

### ISSUE THREAD

**Issue by kevin1sMe** [soulteary/apt-proxy#6]
尝试给centos8 stream设置这个代理，最近看代理能否正常工作，非预期的panic了。

```
2022/06/15 16:10:07 http: superfluous response.WriteHeader call from github.com/soulteary/apt-proxy/server.(*responseWriter).WriteHeader (proxy.go:70)
2022/06/15 16:10:07 192.168.50.202 "GET http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=stock HTTP/1.1" (OK) 130 SKIP 864.326223ms
2022/06/15 16:10:09 192.168.50.202 "GET http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/repodata/repomd.xml HTTP/1.1" (OK) 4473 SKIP 1.762954818s
panic: net/http: abort Handler

goroutine 135 [running]:
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc000100820, {0x782190?, 0xc000010510}, 0xc0001b6100)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/httputil/reverseproxy.go:349 +0xe89
github.com/soulteary/apt-proxy/pkgs/httpcache.(*Handler).passUpstream.func1()
	/home/runner/work/apt-proxy/apt-proxy/pkgs/httpcache/handler.go:254 +0x3d
created by github.com/soulteary/apt-proxy/pkgs/httpcache.(*Handler).passUpstream
	/home/runner/work/apt-proxy/apt-proxy/pkgs/httpcache/handler.go:253 +0x1fb
```

**Comment by soulteary** [comment]
done, https://github.com/soulteary/apt-proxy/releases/tag/v0.4.0 @kevin1sMe
